export const OBTENER_YEAR_ACTUAL_EXITO = " OBTENER_YEAR_ACTUAL_EXITO";

export const OBTENER_MONTH_ACTUAL_EXITO = " OBTENER_MONTH_ACTUAL_EXITO";
export const OBTENER_CANTIDAD_DAYS_MONTH_EXITO =
  "OBTENER_CANTIDAD_DAYS_MONTH_EXITO ";
export const OBTENER_VALUE_DATE_EXITO = "OBTENER_VALUE_DATE_EXITO";

export const OBTENER_VALUE_DATE_ERROR = "OBTENER_VALUE_DATE_ERROR";

export const OBTENER_NOTAS_EXITO = " OBTENER_NOTAS_EXITO";

export const OBTENER_NUMERO_NOTA_POR_DIA_EXITO =
  "  OBTENER_NUMERO_NOTA_POR_DIA_EXITO";

export const ACTUALIZAR_NOTA = "ACTUALIZAR_NOTA";
